//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        public int FurnitureId { get; set; }
        public string FurnitureDescription { get; set; }
        public Nullable<double> FurniturePrice { get; set; }
        public Nullable<int> FurnitureQuantity { get; set; }
        public Nullable<double> FurnitureCost { get; set; }
        public double FurnitureValue { get; set; }
    }
}
